---
- name: Prepare conf dirs for every host in inventory file
  hosts: all
  gather_facts: no
  vars:
    conf_dir: "{{playbook_dir}}/compiled/{{ inventory_hostname }}"
    cli:
      host: "{{ ansible_ssh_host }}"
  
  pre_tasks:
    - set_fact: conf_dir="{{conf_dir}}"


    - name: Remove old config
      file: path={{ conf_dir }} state=absent
      changed_when: False
#      when: commit_changes | match('0')
      always_run: yes
      tags: ['always']

    - name: Create placeholder for building templates
      file: path=compiled/{{ inventory_hostname }}/ state=directory
      changed_when: False
#      when: commit_changes | match('0')
      always_run: yes
      tags: ['always']
  
#- include: show_jun.yml  
#- include: show_cisco.yml
 
- name: build initial conf for every host in inventory
  hosts: all 
  roles:
    - build_conf
#- include: copy_cisco_conf.yml
- include: load_juniper_conf.yml
