---
- name: transfer generated file to IOS
  hosts: cisco
  gather_facts: no
  vars:
    cli:
      host: "{{ ansible_ssh_host }}"
      username: rado
      transport: cli
  #    ssh_keyfile: /home/rado/.ssh/z-id_rsa
  tasks:
  - name: copy files to tftp directory
    copy: src={{ playbook_dir }}/compiled/{{ inventory_hostname }}  dest=/var/lib/tftpboot

  - name: load a config from disk and replace the current config
    script: ./upload_xr.py "{{ ansible_ssh_host }}" "tftp://192.168.1.249/{{ inventory_hostname }}/generated.cfg"
