---
- name: show cisco interfaces
  hosts: cisco
  gather_facts: no
  vars:
    cli:
      host: "{{ ansible_ssh_host }}"
      username: rado
      transport: cli
      ssh_keyfile: /home/rado/.ssh/z-id_rsa   
  tasks:
  - name: run show version on remote devices
    ios_command:
      commands:
        - show  run
      provider: "{{ cli }}"
    register: interfaces
  - debug: var=interfaces.stdout_lines 
